pool:
  name: Default
variables:
  BuildConfiguration: 'Release'

steps:
- script: 'dotnet build Immutable/Apex.Analyzers.Immutable/Apex.Analyzers.Immutable.csproj -c $(BuildConfiguration)'
  displayName: 'dotnet build'
- task: DeleteFiles@1
  inputs:
    Contents: '**/*.trx'
- script: |
   dotnet test Immutable/Apex.Analyzers.Immutable.Test/Apex.Analyzers.Immutable.Test.csproj -c $(BuildConfiguration) --logger "trx;LogFileName=results.trx"
  displayName: 'dotnet test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/results*.trx'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'Unit tests'
